trading:
  default_position_size: 100  # USD
  max_position_size: 1000     # USD
  stop_loss_pct: 0.05         # 5%
  take_profit_pct: 0.10       # 10%
  max_slippage_pct: 0.01      # 1%

risk_management:
  max_daily_loss: 500         # USD
  max_open_positions: 5
  max_portfolio_risk_pct: 0.02 # 2% of portfolio per trade
  position_sizing_method: "fixed"  # "fixed", "percentage", "kelly"

backtest:
  initial_capital: 10000      # USD
  commission_rate: 0.005      # 0.5%
  slippage_rate: 0.001        # 0.1%
  start_date: null           # YYYY-MM-DD format
  end_date: null             # YYYY-MM-DD format

logging:
  level: "INFO"
  file: "logs/trading.log"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
